export enum RoleEnum {
  INFLUENCER = "INFLUENCER",
  COMPANY = "COMPANY",
}

export enum DisponibiliteEnum {
  DISPONIBLE = "DISPONIBLE",
  OCCUPE = "OCCUPE",
  PARTIELLEMENT_DISPONIBLE = "PARTIELLEMENT_DISPONIBLE",
}

export enum TypeCollaborationEnum {
  PLACEMENT_PRODUIT = "PLACEMENT_PRODUIT",
  STORY = "STORY",
  POST = "POST",
  VIDEO = "VIDEO",
  REEL = "REEL",
  LIVE = "LIVE",
  AMBASSADEUR = "AMBASSADEUR",
}

export enum PlateformeEnum {
  INSTAGRAM = "INSTAGRAM",
  TIKTOK = "TIKTOK",
  YOUTUBE = "YOUTUBE",
  FACEBOOK = "FACEBOOK",
  TWITTER = "TWITTER",
  LINKEDIN = "LINKEDIN",
  SNAPCHAT = "SNAPCHAT",
}

export enum FrequencePublicationEnum {
  QUOTIDIENNE = "QUOTIDIENNE",
  HEBDOMADAIRE = "HEBDOMADAIRE",
  BI_HEBDOMADAIRE = "BI_HEBDOMADAIRE",
  MENSUELLE = "MENSUELLE",
}
